# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11XmQRiZZ9oeA4-ivJDyqj7cYu7gPTiCc
"""

import textwrap

nucleotide_sequence = "CGCGCGTCGGCGCCGCTGCCAACCCCGCTCTGCGATCTCGGGCCCTCCCG"
nucleotide_sequence = nucleotide_sequence.replace("T","U")

nucleotide_sequence[:]

nucleotide_sequence = [nucleotide_sequence[n:n+3] for n in range(0, len(nucleotide_sequence), 3)]
nucleotide_sequence

nucleotide_sequence_lookup_table = {
    'AUG': "M",
    'UUU': "F",
    'UUC': "F",
    'UUA': "L",
    'UUG': "L",
    'CUU': "L",
    'CUC': "L",
    'CUA': "L",
    'CUG': "L",
    'AUU': "I",
    'AUC': "I",
    'AUA': "I",
    'GUU': "V",
    'GUC': "V",
    'GUA': "V",
    'GUG': "V",
    'UCU': "S",
    'UCC': "S",
    'UCA': "S",
    'UCG': "S",
    'CCU': "P",
    'CCC': "P",
    'CCA': "P",
    'CCG': "P",
    'ACU': "T",
    'ACC': "T",
    'ACA': "T",
    'ACG': "T",
    'GCU': "A",
    'GCC': "A",
    'GCA': "A",
    'GCG': "A",
    'UAU': "Y",
    'UAC': "Y",
    'UAA': "STOP",
    'UAG': "STOP",
    'CAU': "H",
    'CAC': "H",
    'CAA': "Q",
    'CAG': "Q",
    'AAU': "N",
    'AAC': "N",
    'AAA': "K",
    'AAG': "K",
    'GAU': "D",
    'GAC': "D",
    'GAA': "E",
    'GAG': "E",
    'UGU': "C",
    'UGC': "C",
    'UGA': "STOP",
    'UGG': "W",
    'CGU': "R",
    'CGC': "R",
    'CGA': "R",
    'CGG': "R",
    'AGU': "S",
    'AGC': "S",
    'AGA': "R",
    'AGG': "R",
    'GGU': "G",
    'GGC': "G",
    'GGA': "G",
    'GGG': "G",
  }

Amino_acid_list = [nucleotide_sequence_lookup_table [i] for i in nucleotide_sequence[0:-1]]
Amino_acid_list

Amino_acid_lookup_table = {
    'A': "Alanine",
    'R': "Arginine",
    'D': "Aspartic Acid",
    'B': "Aspartic acid",
    'C': "Cysteine",
    'Q': "Glutamine acid",
    'E': "Glutamic acid",
    'Z': "Glutamine",
    'G': "Glycine",
    'H': "Histidine",
    'I': "Isoleucine",
    'L': "Leucine",
    'K': "Lysine",
    'M': "Methionine",
    'F': "Phenylalanine",
    'P': "Proline",
    'S': "Serine",
    'T': "Threonine",
    'W': "Tryptophan",
    'Y': "Tyrosine",
    'V': "Valine",
    'N': "",
    'STOP' : "STOP"
  }

[Amino_acid_lookup_table [i] for i in Amino_acid_list[0:-1]]